config/routes.rb
TrackMyCourses::Application.routes.draw do
  resources :dashboard
  resources :courses

  resource :account do
    get :sign_out, on: :member
    get :subscribe, on: :member
    resources :subscriptions
  end

  root :to => 'home#index'
  match "/auth/:provider/callback" => "accounts#create"
end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :course_ids, :uid, :twitter_username, :twitter_notify
  
  has_many :subscriptions
  has_many :courses, :through => :subscriptions
  has_many :authentications

  def authenticated_with?(provider)
    authentications.any? { |authentication| authentication.provider == provider }
  end
end

app/models/assignment.rb
class Assignment < Section
  attr_accessible :due_date
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :nickname, :provider, :uid

  belongs_to :account
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  attr_accessible :title, :course, :number

  belongs_to :course
  has_many :sections
  has_many :lectures
  has_many :assignments

  def as_json(options={})
    super include: { course: { include: :platform }, lectures: {}, assignments: {} }
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :description, :logo_url, :platform_id, :title, :url, :platform, :start_date

  belongs_to :platform
  has_many :chapters

  scope :started, -> { where "start_date <= ?", Date.today }

  def started?
    Date.today >= start_date
  end

  def chapter_at_week(week)
    chapter_number = week - start_date.cweek + 1
    self.chapters.find_by_number chapter_number
  end

  def as_json(options={})
    super :include => :platform
  end
end

app/models/lecture.rb
class Lecture < Section
  attr_accessible :duration, :practice_count, :score_count
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  attr_accessible :logo_url, :name, :url

  has_many :courses

  def self.[](name)
    find_by_name(name.to_s)
  end

  def credentials
    self.class.config[name].symbolize_keys
  end

  protected

  def self.config
    @config ||= YAML::load(ERB.new(File.read(File.join(Rails.root, 'config', 'platforms.yml'))).result)[Rails.env]
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :title, :url, :chapter

  belongs_to :chapter
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :course
  belongs_to :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :find_account, only: [:create]

  def create
    if logged_in?
      @account = current_user
      add_authentication
    else
      if @account.nil?
        create_account
        add_authentication
      end

      sign_in
    end

    redirect_to root_url protocol: 'http'
  end

  def update
    current_user.update_attribute(:twitter_notify, params[:twitter_notify]) if (params.key?(:twitter_notify) && logged_in? && current_user.authenticated_with?("twitter"))
 
    render json: :nothing, status: 200
  end

  def sign_out
    session[:user_id] = nil
    session[:course_ids] = nil
    redirect_to root_url protocol: 'http'
  end

  def subscribe
    if logged_in?
      current_user.toggle! :twitter_notify
    end
    respond_to do |format|
      format.js
    end
  end

  protected

  def find_account
    @account = Account.joins(:authentications).where('authentications.uid = ?', uid).first
  end

  def create_account
    @account = Account.create! :course_ids => session[:course_ids]
  end

  def sign_in
    session[:user_id] = @account.id
  end

  def oauth_data
    request.env["omniauth.auth"].to_hash
  end

  def add_authentication
    @account.authentications.create! :uid => uid, :provider => provider, :nickname => nickname
  end

  def nickname
    oauth_data['info']['nickname']
  end

  def provider
    oauth_data['provider']
  end

  def uid
    oauth_data['uid']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def current_user
    session.key?(:user_id) ? Account.find_by_id(session[:user_id]) : nil
  end

  def logged_in?
    current_user.present?
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :find_courses
  
  def index
    render :json => @courses
  end

  protected

  def search?
    params.key? :search
  end

  def search_query
    "%#{params[:search]}%"
  end

  def find_courses
    @courses = search? ?
                 Course.where('title LIKE ?', search_query) :
                 Course.all
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    courses = user_courses
    chapters = courses.map { |course| course.chapter_at_week(params[:week].to_i)}
    chapters = chapters.compact

    if chapters.any?
      assignments = chapters.map(&:assignments).flatten
      lectures = chapters.map(&:lectures).flatten
      total_lecture_count = lectures.count
      total_practice_count = lectures.map(&:practice_count).inject(&:+)
      total_assignment_count = assignments.size
      total_lecture_duration = lectures.map(&:duration).inject(&:+)
    else
      total_lecture_count = 0
      total_practice_count = 0
      total_assignment_count = 0
      total_lecture_duration = 0
    end

    respond_to do |format|
      format.html
      format.json do
        render json: {
          total_lecture_count: total_lecture_count.to_i,
          total_practice_count: total_practice_count.to_i,
          total_assignment_count: total_assignment_count.to_i,
          total_lecture_duration: total_lecture_duration.to_i,
          chapters: chapters
        }
      end
    end
  end

  protected

  def user_courses
    if logged_in?
      current_user.courses
    else
      if session[:course_ids] 
        Course.find session[:course_ids]
      else
        []
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      redirect_to current_user.courses.any? ? dashboard_index_url(protocol: 'http') : account_subscriptions_url(protocol: 'http')
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    session[:course_ids] = params[:course_ids]
    
    if logged_in?
      current_user.update_attributes :course_ids => params[:course_ids]
    end
    
    render json: '', status: 201
  end

  def index
    respond_to do |format|
      format.html
      format.json { render :json => json }
    end
  end

  protected

  def json
    course_ids = logged_in? ? current_user.courses.map(&:id) : session[:course_ids]
    { course_ids: course_ids || [] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/subscribe.js.erb
$("#subscribe").text("<%= (controller.__send__ :current_user).twitter_notify ? 'unsubscribe' : 'subscribe' %>");

app/views/dashboard/index.html.slim
.dashboard
  .row 
    .twelve.columns
      h2 Dashboard
      .row
        .nine.columns 
          #weeks
            .row
              .four.columns.previous
                a#prev-week
                  | Previous week
                  span.date 08.10 - 14.10

              .four.columns.current
                a#current-week
                  | Go to the current week
                span.date 08.10 - 14.10

              .four.columns.next
                a#next-week
                  | Next week
                  span.date 08.10 - 14.10

          #summary
            .row
              .four.columns.lectures
                h3 
                  em 0
                  |  lectures
                h5
              .four.columns.practicies
                h3
                  em 0
                  |  practices
              .four.columns.assigments
                h3
                  em 0
                  |  assignments

          #chapters

        .three.columns.sidebar
          = link_to "My courses", account_subscriptions_path, class: "bigbutton back"
          .my-accounts
            .header
              h2 
                | Accounts 
                - if controller.__send__ :logged_in?    
                  a.sign_out href="#{sign_out_account_url protocol: 'http'}" Sign out
            ul.accounts
              li.twitter class="#{'connected' if controller.__send__ :logged_in?}"

                - if controller.__send__ :logged_in? 
                  - if (controller.__send__ :current_user).authenticated_with?('twitter')
                    span 
                      = (controller.__send__ :current_user).authentications.find_by_provider('twitter').nickname
                      |  (
                      a#subscribe href="#{subscribe_account_path}" data-remote="true" #{(controller.__send__ :current_user).twitter_notify ? "unsubscribe" : "subscribe"}
                      | )
                    / a.remove href="#" remove
                  - else
                    a href="/auth/twitter" title="Sign in with twitter" Connect
                - else
                  a href="/auth/twitter" title="Sign in with twitter" Sign in with twitter

              li.facebook
                - if controller.__send__ :logged_in?
                  - if (controller.__send__ :current_user).authenticated_with?('facebook')
                    span = (controller.__send__ :current_user).authentications.find_by_provider('facebook').nickname
                    / a.remove href="#" remove
                  - else
                    a href="/auth/facebook" title="Sign in with facebook" Connect
                - else
                  a href="/auth/facebook" title="Sign in with facebook" Sign in with facebook
                  
              li.github
                a.not-supported href="#" title="Sorry, not supported yet" Not supported yet
                a.remove href="#" remove
              li.google
                a.not-supported href="#" title="Sorry, not supported yet" Not supported yet
                a.remove href="#" remove
                 
              li Connect your network accounts to access your dashboard from other devices

app/views/home/index.html.slim
.row
  .twelve.columns.main
    .row
      .nine.columns
        #slider
          img src="/images/slide1.png" alt="slide_1"
          img src="/images/slide2.png" alt="slide_2"
          img src="/images/slide3.png" alt="slide_3"

      .three.columns.sidebar
        = link_to "Start tracking", account_subscriptions_path, class: "bigbutton"
        #network_accounts_block
          p
            | Sign in with 
            span#network_accounts_trigger network account
          ul#network_accounts
            li: a.twitter href="/auth/twitter" title="Sign in with Twitter" twitter
            li: a.facebook href="/auth/facebook" title="Sign in with Facebook" facebook
            li: a.google.not-supported href="#" title="Sorry, not supported yet" google
            li: a.github.not-supported href="#" title="Sorry, not supported yet" github

        ul.platforms
          li: a.edx href="https://www.edx.org/" target="_blank" title="edX" edX 
          li
            span.coursera target="_blank" title="coursera" coursera
            span.not-supported (coming soon)
          li
            span.udacity title="Not supported yet, try later" udacity
            span.not-supported (coming soon)
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "TrackMyCourses" %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/header' %>
	<%= yield %>
	<%= render 'shared/footer' %> 
	<%- if Rails.env.production? %>
		<script type="text/javascript">
		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-35561985-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		</script>
	<% end %>
</body>
</html>

app/views/shared/_footer.html.slim
footer
  .row
    .twelve.columns
      p 
        | Created by 
        a.octopus href="http://railsrumble.com/entries/115-octopus" target="_blank" octopus

      a.github href="https://github.com/" target="_blank"

app/views/shared/_header.html.slim
header.row
  .nine.columns
    h1 = link_to "TrackMyCourses", root_path, id: "logo"
  .three.columns
    q 
      | …may the 
      em course 
      span.right be with you

app/views/subscriptions/index.html.slim
.subscription#composition-page
  .row 
    .twelve.columns
      h2 Choose your courses to track
      .row
        .nine.columns 
          / form#search
          /   input type="text" placeholder="Find your course..."
          /   input type="submit"
          ul.block-grid.two-up#course-list
            / - 5.times do
            /   li
            /     article.coursera
            /       .illustration style="background-image: url('http://placehold.it/350x240&text=course+logo')"
            /         img src="http://placehold.it/350x240&text=course+logo" alt="sample optional course"
            /       h1 sample optional course
            /       a.add href="#" track it!

        .three.columns.sidebar
          = link_to "Go to dashboard", dashboard_index_path, class: "bigbutton", id: "to_dashboard", title: "Add courses first"
          .my-courses
            .header
              h2 My courses          
            #selected_courses
              / - 5.times do
              /   article.edx
              /     .illustration style="background-image: url('http://placehold.it/350x240&text=course+logo')"
              /       img src="http://placehold.it/350x240&text=course+logo" alt="sample selected course"
              /     h1 Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              /     a.remove href="#" remove

app/views/users/new.html.slim
.subscription
  .row 
    .twelve.columns
      h2 Choose your courses to track
      .row
        .nine.columns 
          form#search
            input type="text" placeholder="Find your course..."
            input type="submit"
          ul.block-grid.two-up.course-list
            - 5.times do
              li
                article.coursera
                  .illustration style="background-image: url('http://placehold.it/350x240&text=course+logo')"
                    img src="http://placehold.it/350x240&text=course+logo" alt="sample optional course"
                  h1 sample optional course
                  a.add href="#" track it!

        .three.columns.sidebar
          = link_to "Go to dashboard", dashboard_index_path, class: "bigbutton"
          .my-courses
            .header
              h2 My courses          
            #selected_courses
              - 5.times do
                article.coursera
                  .illustration style="background-image: url('http://placehold.it/350x240&text=course+logo')"
                    img src="http://placehold.it/350x240&text=course+logo" alt="sample selected course"
                  h1 sample selected course
                  a.remove href="#" remove